import React from 'react';

export function getClients() {
  return {
    'SmartyPants Vitamins': {
      tehnologies: 'WordPress, Shopify',
      country: '🇺🇸',
      link: 'https://www.smartypantsvitamins.com/',
      image: 'smartypantsvitamins.jpeg',
    },
    'CAMP DAVID & SOCCX': {
      tehnologies: 'Oxid e-Commerce',
      country: '🇩🇪',
      link: 'https://www.campdavid-soccx.de/',
      image: 'campdavid.jpeg',
    },
    Arduino: {
      tehnologies: 'Magento',
      link: 'https://store.arduino.cc/',
      country: '🇮🇹',
      image: 'arduino.jpeg',
    },
    Tesori: {
      tehnologies: 'Magento, WordPress',
      country: '🇳🇴',
      link: 'https://tesori.no/',
      image: 'tesori.jpeg',
    },
    BilXtra: {
      tehnologies: 'Magento, WordPress, Ruby on Rails',
      country: '🇳🇴',
      link: 'https://bilxtra.no/',
      image: 'bilxtra.jpeg',
    },
    Pickles: {
      tehnologies: 'Magento, WordPress',
      country: '🇳🇴',
      link: 'https://pickles.no/',
      image: 'pickles.jpeg',
    },
    JumpKing: {
      tehnologies: 'WordPress, WooCommerce',
      country: '🇳🇴',
      link: 'https://jumpking.no/',
      image: 'jumpking.jpeg',
    },
    Smartlapper: {
      tehnologies: 'Magento, WordPress',
      country: '🇳🇴',
      link: 'https://smartlapper.no/',
      image: 'smartlapper.jpg',
    },
    'Lava Art': {
      tehnologies: 'WordPress, WooCommerce, WPML',
      country: '🇳🇴',
      link: 'https://lavaart.com/',
      image: 'lavaart.jpeg',
    },
    Bedtime: {
      tehnologies: 'WordPress, WooCommerce',
      country: '🇳🇴',
      link: 'https://bedtime.no/',
      image: 'bedtime.jpeg',
    },
    'Naturlig Liv': {
      tehnologies: 'WordPress, Magento',
      country: '🇳🇴',
      link: 'https://natuligliv.no/',
      image: 'natuligliv.jpeg',
    },
    Blahface: {
      tehnologies: 'Ruby on Rails',
      country: '🇺🇸',
      link: 'https://blahface.com/',
      image: 'blahface.jpeg',
    },
    'Ulleval Kiropraktor': {
      tehnologies: 'WordPress',
      country: '🇳🇴',
      link: 'https://www.ullevalkiropraktor.no/',
      image: 'ullevalkiropraktor.jpg',
    },
    'Omage Cure': {
      tehnologies: 'WordPress, WooCommerce',
      country: '🇳🇴',
      link: 'https://omegacure.no/',
      image: 'omegacure.jpeg',
    },
    Warholms: {
      tehnologies: 'Magento',
      country: '🇳🇴',
      link: 'https://warholms.no/',
      image: 'warholms.jpeg',
    },
    IMI: {
      tehnologies: 'WordPress, Zapier, Notion',
      country: '🇳🇱',
      link: 'https://imimediation.org/',
      image: 'imimediation.jpeg',
    },
    'Made By Berit': {
      tehnologies: 'WooCommerce, WordPress',
      country: '🇳🇴',
      link: 'https://beritnordstrand.no/',
      image: 'beritnordstrand.jpeg',
    },
    'CAMP DAVID & SOCCX B2B': {
      tehnologies: 'Ruby On Rails, Magento',
      link: 'https://www.campdavid-soccx.de/',
      country: '🇩🇪',
      image: 'clinton-b2b.jpeg',
    },
    DNBS: {
      tehnologies: 'WooCommerce, WordPress',
      substack: 'Klarna, WPML',
      country: '🇳🇴',
      link: 'https://www.dnbs.no/en/',
      image: 'dnbs.jpeg',
    },
    'Sommer Ballett': {
      tehnologies: 'WooCommerce, WordPress',
      substack: 'Klarna, WPML',
      country: '🇳🇴',
      link: 'https://www.sommerballett.no/en/',
      image: 'sommerballett.jpeg',
    },
    Khujo: {
      tehnologies: 'Magento, WordPress',
      substack: 'Redis, SalesForce, Optimizely, Amazon CloudFront',
      country: '🇩🇪',
      link: 'https://www.khujo.com/',
      image: 'khujo.jpeg',
    },
    MedLearn: {
      tehnologies: 'WordPress',
      substack: 'Redis',
      country: '🇳🇴',
      link: 'https://medlearn.no/',
      image: 'medlearn.jpeg',
    },
    'GR Drukkerij': {
      tehnologies: 'WordPress, WooCommece',
      substack: 'Klarna',
      country: '🇳🇱',
      link: 'https://grdruk.nl/',
      image: 'grdruk.jpeg',
    },
    'Living Autism': {
      tehnologies: 'Ruby On Rails, WordPress',
      substack: 'Redis',
      country: '🇬🇧',
      link: 'https://livingautism.co.uk/',
      image: 'livingautism.jpg',
    },
    Skntific: {
      tehnologies: 'Ruby On Rails',
      substack: 'Redis, Nginx',
      country: '🇳🇴',
      link: 'https://skintific.no/',
      image: 'skintific.jpeg',
    },
    LeCollab: {
      tehnologies: 'Ruby On Rails',
      substack: 'Redis, Nginx',
      country: '🇺🇸',
      link: 'https://LeCollab.com/',
      image: 'collab.jpg',
    },
    Selekkt: {
      tehnologies: 'Magento, Algolia',
      substack: 'Nginx',
      country: '🇩🇪',
      link: 'https://selekkt.com/',
      image: 'selekkt.jpeg',
    },
    'Ucon Acrobatics': {
      tehnologies: 'Magento, Shopify',
      substack: 'Redis, Nginx',
      country: '🇩🇪',
      link: 'https://ucon-acrobatics.com/',
      image: 'ucon-acrobatics.jpeg',
    },
    Mascolori: {
      tehnologies: 'Magento',
      substack: 'Redis, Nginx',
      country: '🇳🇱',
      link: 'https://mascolori.nl/',
      image: 'mascolori.jpeg',
    },
    Vaktrommet: {
      tehnologies: 'Magento, Algolia, Custom JS',
      substack: 'Nginx',
      country: '🇳🇴',
      link: 'https://vaktrommet.no/',
      image: 'vaktrommet.jpeg',
    },
    'Tokyo Jane': {
      tehnologies: 'Magento, WordPress',
      substack: 'Nginx',
      country: '🇩🇪',
      link: 'https://tokyojane.com/',
      image: 'tokyojane.jpeg',
    },
    Etiketta: {
      tehnologies: 'Nest.js, React',
      substack: 'Nginx, Express JS',
      country: '🇸🇪',
      link: 'https://etiketta.se/',
      image: 'etiketta.jpeg',
    },
    PosterStar: {
      tehnologies: 'WooCommerce, WPML',
      substack: 'Klarna',
      country: '🇸🇪',
      link: 'https://posterstar.websitetotal.com/',
      image: 'posterstar.jpeg',
    },
    'Privatni Casovi': {
      tehnologies: 'Ruby On Rails',
      substack: 'Klarna',
      country: '🇷🇸',
      link: 'https://privatni-casovi.net/',
      image: 'privatni-casovi.jpeg',
    },
    'Fachwelt Verlag': {
      tehnologies: 'WordPress',
      substack: 'Klarna',
      country: '🇩🇪',
      link: 'https://www.fachwelt-verlag.de/',
      image: 'fachwelt-verlag.jpg',
    },
    'IB Expo': {
      tehnologies: 'Ruby On Rails',
      substack: 'Klarna',
      country: '🇳🇴',
      link: 'https://ib-expo.com/',
      image: 'ib-expo.jpg',
    },
    Luado: {
      tehnologies: 'Ruby On Rails',
      substack: 'Stripe, Twilio',
      country: '🇳🇴',
      link: 'https://luado.no/',
      image: 'luado.jpeg',
    },
    'Ruden Energy': {
      tehnologies: 'Craft CMS',
      substack: 'Klarna',
      country: '🇳🇴',
      link: 'https://rudenas.com/',
      image: 'rudenas.jpeg',
    },
    'Prominent Immobilien': {
      tehnologies: 'WordPress',
      substack: 'Klarna',
      country: '🇩🇪',
      link: 'https://www.prominent-immobilien.com/',
      image: 'prominent-immobilien.jpg',
    },
    ALP: {
      tehnologies: 'Craft CMS',
      substack: 'Klarna',
      country: '🇳🇴',
      link: 'https://alpinogfjell.no/',
      image: 'alpinogfjell.jpeg',
    },
    'Bare Bra Barnemat': {
      tehnologies: 'WordPress',
      substack: 'Klarna',
      country: '🇳🇴',
      link: 'https://www.barebrabarnemat.no/',
      image: 'barebrabarnemat.jpg',
    },
    Industry24h: {
      tehnologies: 'WordPress',
      substack: 'Klarna',
      country: '🇩🇪',
      link: 'https://industry24h.com/',
      image: 'industry24h.jpeg',
    },
  };
}
